name: BarudakMC
version: '${project.version}'
main: com.aspectxlol.barudakmc.BarudakMC
api-version: '1.21'
authors: [ "aspectxlol" ]
description: "A plugin for minecraft"
load: STARTUP
commands:
  map:
    description: create a map from an image
    usage: /map
    permission: BarudakMC.createMap